[uwsgi]

http = 0.0.0.0:8092

# 项目目录
chdir = /app

# 指定项目的Application
module = main:application

master = true

buffer-size = 165536

# 开多少进程
processes = 8

# 每个进程上有多少线程
threads = 4

need-app = true
die-on-term = true
single-interpreter = true
vacuum = true
